version: "3.7"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-cyberbully}"
    image: cyberbully-data-processing
    container_name: cyberbully-data-processing-container
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./creds/cyberbully-b0d2e22dab21.json
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-charles}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME}/.config/gcloud
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    init: true


